### ISSUE TITLE
Clickable steps

### ISSUE THREAD

**Issue by IonutNegru87** [badoualy/stepper-indicator#11]
Hello,

How can I make the steps clickable? Do you intend to add support for this in the near future? 
I've also been wandering if the bullet inside (the current step indicator can be remove/replaced by an selector at the bottom of the circle - like on the TabLayout.Tab current tab indicator)

**Comment by badoualy** [comment]
Hi,

for the clickable step feature, it should be quite easy to implement, just have to set click listener and test event position and compare with each step circle position (which should be stored already in a field so easy).

For the bullet part, don't plan on working that anytime soon sorry :)

**Comment by IonutNegru87** [comment]
Hello,

Thanks for the reply. I've made some changes to your project and I've added the support for click events for the steps already. I'll make a pull request the following days if you want to integrate it.
I am also working on adding support for replacing the bullets with number indicators and adding another way for current step indicator (as the bullet doesn't work for that flow anymore :D). I'll make a separate pull request for that if you want to add it to the project.

Thank you and have a good day.

**Comment by badoualy** [comment]
Awesome! 
I'll merge the click events support,

for the "replacing the bullet with number indicator", it'll depend on the implementation, if we can easily switch from one to the other, it should be ok :)

**Comment by IonutNegru87** [comment]
I've created an pull request for the steps click event support:
https://github.com/badoualy/stepper-indicator/pull/12

**Comment by badoualy** [comment]
Great, I'll check that ASAP

**Comment by badoualy** [comment]
Clickable steps done in 1.0.4 :)

**Comment by IonutNegru87** [comment]
Thank you.

I'm working on the other customization now, I hope today to have that ready also :D

**Comment by IonutNegru87** [comment]
Hello,

I've made an pull request for the other changes: https://github.com/badoualy/stepper-indicator/pull/14. Please have a look at it when you have time :D

Thanks.
