### ISSUE TITLE
IllegalArgumentException at version 1.0.4

### ISSUE THREAD

**Issue by toanvc** [badoualy/stepper-indicator#15]
I think problem here is indicators be initialized after invoking computeStepsClickAreas(), that make indicators variable be null:

>  computeStepsClickAreas(); // update the position of the steps click area also
> 
>  indicators = new float[stepCount];

I just switched 2 lines and it works.

Logs:

> Caused by: java.lang.IllegalArgumentException: indicators wasn't setup yet. Make sure the indicators are initialized and setup correctly before trying to compute the click area for each step!
>                                                                                           at com.badoualy.stepperindicator.StepperIndicator.computeStepsClickAreas(StepperIndicator.java:291)
>                                                                                           at com.badoualy.stepperindicator.StepperIndicator.compute(StepperIndicator.java:256)
>                                                                                           at com.badoualy.stepperindicator.StepperIndicator.setStepCount(StepperIndicator.java:410)
>                                                                                           at com.badoualy.stepperindicator.StepperIndicator.init(StepperIndicator.java:210)
>                                                                                           at com.badoualy.stepperindicator.StepperIndicator.<init>(StepperIndicator.java:151)
>                                                                                           at com.badoualy.stepperindicator.StepperIndicator.<init>(StepperIndicator.java:0)`

**Comment by aliusa** [comment]
I also experiencing same problem with 1.0.4.

**Comment by IonutNegru87** [comment]
Hello,

This can be fixed by calling the method `computeStepsClickAreas()` right after calling `compute()` method.
There is a new pull request with new features which doesn't have this issue. Meanwhile, just call that method right after compute() and should work.

**Comment by badoualy** [comment]
It'll be fixed in next version, coming soon

**Comment by drinfernoo** [comment]
Is this fix coming soon? I intended to use this library, but this crash is holding me back :(

**Comment by aliusa** [comment]
@drinfernoo, just use 1.0.3 as if now.
