### ISSUE TITLE
Step name

### ISSUE THREAD

**Issue by aliusa** [badoualy/stepper-indicator#16]
I would like to have each step have it's page name. Page title would go below step circle.

**Comment by aliusa** [comment]
FragmentStatePagerAdapter would need to have:

```
private List<String> mFragmentTitleList;

@Override
  public CharSequence getPageTitle(int position) {
    return mFragmentTitleList.get(position);
  }
```

to get titles.

Or manualy:...

```
@Override
public CharSequence getPageTitle(int position) {
  switch (position) {
    case 1: return "Page 1";
    case 2: return "Page 2";
  }
  return null;
}
```

**Comment by aliusa** [comment]
Implementing #16 to show step title below step indicator.
Somewhy I can't do PR.

**Comment by badoualy** [comment]
Label feature was added by @rakshakhegde
