### ISSUE TITLE
IllegalArgumentException: indicators wasn't setup yet.

### ISSUE THREAD

**Issue by davidkrauser** [badoualy/stepper-indicator#22]
I get the following error whenever I try to use this library: 

```
IllegalArgumentException: indicators wasn't setup yet. Make sure the indicators are initialized and setup correctly before trying to compute the click area for each step!
```

It looks like `compute()` calls `computeStepsClickAreas()`, which depends on a valid array of `indicators`; however, the `indicators` array isn't initialized until after the call to `computeStepsClickAreas()`.

Or am I using the library incorrectly? This is against v1.0.4

**Comment by davidkrauser** [comment]
It looks like this may be fixed in the master branch. Any plans to cut a new version soon?

**Comment by badoualy** [comment]
I'll release a new version tomorrow, until then you should be able to use it with the latest commit hash

``` gradle
compile 'com.github.badoualy:stepper-indicator:3675b4dd8e'
```

**Comment by davidkrauser** [comment]
Sounds good, thanks :-)
