### ISSUE TITLE
Automatically calculate stepCount based on PagerAdapter.getCount()

### ISSUE THREAD

**Issue by drinfernoo** [badoualy/stepper-indicator#24]
Is this something that would be doable?

**Comment by k0shk0sh** [comment]
this actually should be the default behaviour since not everyone want to setup the counter through the xml.

**Comment by rakshakhegde** [comment]
This is in fact the default behaviour.

**Comment by paulVulog** [comment]
Confirmed : this is the current behavior. (you can only override the count after  the setViewPager call)

**Comment by badoualy** [comment]
+1 see https://github.com/badoualy/stepper-indicator/blob/master/library/src/main/java/com/badoualy/stepperindicator/StepperIndicator.java#L1163
