### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: indicators wasn't setup yet. Make sure the indicators are initialized and setup correctly before trying to compute the click area for each step!

### ISSUE THREAD

**Issue by k0shk0sh** [badoualy/stepper-indicator#25]
following your example code i have setup the indicator like below: 

```
        <com.badoualy.stepperindicator.StepperIndicator
            android:id="@+id/indicator"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginEnd="@dimen/spacing_sLarge"
            android:layout_marginStart="@dimen/spacing_sLarge"
            android:layout_marginTop="@dimen/spacing_sLarge"
            app:stpi_stepCount="5"/>
```

but the application crash as soon as the activity start, the root cause would be:

```
private void compute() {
    computeStepsClickAreas(); // update the position of the steps click area also
```

how are you calling this method before initialising the `indicators` ? this immediately throw an exception which shouldn't by any right to be throwing. 

forgot to mention that im using `compile 'com.github.badoualy:stepper-indicator:1.0.4'` after i cloned the repo, i see that you actually have fixed that by replacing the method call to the last line of the `compute()` method. are you planning to push an update soon? as this is a really big STOP for anyone likes to use your library. 

anytime soon to fix this?

thanks

**Comment by badoualy** [comment]
Just released 1.0.6 :)

**Comment by badoualy** [comment]
Just released 1.0.6 :)

**Comment by k0shk0sh** [comment]
is there anything new from the time i cloned the library? like four hours ago. because i have modified the library abit to suit my case. 
and thank you btw.

**Comment by badoualy** [comment]
Nope, I just fixed the javadoc that was not compiling :)
