### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by jcaruso001** [badoualy/stepper-indicator#27]
> Error:(24, 13) Failed to resolve: com.github.badoualy:stepper-indicator:1.0.6

I'm getting the above error.

**Comment by badoualy** [comment]
Did you add jitpack?
```
repositories {
    // ...       
    maven { url "https://jitpack.io" }
}
```

**Comment by jcaruso001** [comment]
No, the sample doesn't have it in there and I normally don't need to add maven.

**Comment by jcaruso001** [comment]
@badoualy I was able to get the compile working, however it's throwing:

`Unable to start activity ComponentInfo{com.bedgear.pillowid/com.bedgear.pillowid.TypeActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.badoualy.stepperindicator.StepperIndicator`


Also this error:

`indicators wasn't setup yet. Make sure the indicators are initialized and setup correctly before trying to compute the click area for each step!`

I copied it from the sample so I'm not sure what I'm doing wrong.

**Comment by badoualy** [comment]
Did you use version 1.0.6?

**Comment by jcaruso001** [comment]
@badoualy In my attempt to get it to compile; I downgraded and forgot to update it back when I added maven. Thanks for your help!

**Comment by marceloaraujo** [comment]
@jcaruso001 How did you solve your problem? I've been having the same problem here.

**Comment by jcaruso001** [comment]
@marceloaraujo I think it was a problem with the items in my gradle.

**Comment by marceloaraujo** [comment]
@jcaruso001 I've solved the problem. Actually, the problem was my build.gradle, I've put the line `maven { url "https://jitpack.io" }` on wrong place. Thank you.
