### ISSUE TITLE
enabling title in step indicator

### ISSUE THREAD

**Issue by pouriabagheri** [badoualy/stepper-indicator#39]
Hi @badoualy @rakshakhegde 
I understand you have added the title to the step indicator Master branch. However it is not available in release 1.0.6. so i was wondering if you are going to make a release anytime soon ? Im really interested in the title feature and would use it if it's possible?
can you guid me on which fork to download for that feature with most stability?
Regards.

**Comment by rakshakhegde** [comment]
Follow the instructions at: https://jitpack.io/#rakshakhegde/stepper-indicator/601db0230c

This one uses my forked repo.
