### ISSUE TITLE
Classes could not be instantiated

### ISSUE THREAD

**Issue by permadart** [badoualy/stepper-indicator#7]
I'm getting this error on my XML file when on design mode.

> java.lang.NoClassDefFoundError: com/badoualy/stepperindicator/R$color
>     at com.badoualy.stepperindicator.StepperIndicator.init(StepperIndicator.java:104)
>     at com.badoualy.stepperindicator.StepperIndicator.<init>(StepperIndicator.java:91)
>     at com.badoualy.stepperindicator.StepperIndicator.<init>(StepperIndicator.java:86)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:465)
>     at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
>     at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
>     at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:178)
>     at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:247)
>     at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:171)
>     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
>     at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
>     at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
>     at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
>     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
>     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>     at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:317)
>     at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
>     at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
>     at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
>     at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
>     at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
>     at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
>     at com.android.tools.idea.rendering.RenderTask.lambda$inflate$58(RenderTask.java:659)
>     at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:380)
>     at com.android.tools.idea.rendering.RenderTask.inflate(RenderTask.java:659)
>     at com.android.tools.idea.uibuilder.model.NlModel.inflate(NlModel.java:327)
>     at com.android.tools.idea.uibuilder.model.NlModel.updateModel(NlModel.java:373)
>     at com.android.tools.idea.uibuilder.model.NlModel$1.run(NlModel.java:237)
>     at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
>     at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
>     at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
>     at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:282)
>     at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
>     at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
>     at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
>     at com.intellij.util.Alarm$Request.run(Alarm.java:389)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
>     at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

What could it be causing it?

**Comment by badoualy** [comment]
Are you using the latest version?
I checked on my side, looks like the EditMode doesn't like `ContextCompat.getColor()` method, I'll investigate and push a fix ASAP

**Comment by permadart** [comment]
I am. Thanks, I appreciate it.

**Comment by badoualy** [comment]
Sorry for the delay, should be fixed with last commit, can you check please? :smile: 
ps: also released as 1.0.3
